name: nyancoin-core # you probably want to 'snapcraft register <name>'
version: '2.1.0'
summary: Reference client of Nyancoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Nyancoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Much like Litecoin, Nyancoin currently employs a simplified variant of scrypt. MIT licenced.
base: core18
